- name: Mkdir /opt/demo
  file: 
    path=/opt/demo 
    state=directory
  become: yes

- name: Download JAR File to the demo directory
  become: yes
  maven_artifact:
    group_id: "com.employee"
    artifact_id: "employee"
    extension: jar
    version: "0.0.1-SNAPSHOT"
    repository_url: 'http://34.227.71.136:8081/repository/develop/'
    username: admin
    password: admin
    state: present
    dest: /opt/demo/
    mode: 0755

- name: Ensure app is configured
  become: yes
  template:
    src: application.properties.j2
    dest: /opt/demo/application.properties

- name: Ensure logging is configured
  become: yes
  template:
    src: logback-spring.xml.j2
    dest: /opt/demo/logback-spring.xml

- name: Install demo systemd unit file
  become: yes
  template: src=demo.service.j2 dest=/etc/systemd/system/demo.service

- name: Start demo
  become: yes
  systemd: state=restarted name=demo daemon_reload=yes