- name: Mkdir /opt/demo
  file: 
    path=/opt/demo 
    state=directory
  become: yes

- name: Delete existing Jar
  become: yes
  file:
    path: "/opt/demo/employee-1.0.0-SNAPSHOT.jar"
    state: absent
    
- name: Download JAR File to the demo directory
  become: yes
  maven_artifact:
    group_id: "com.employee"
    artifact_id: "employee"
    extension: jar
    version: "1.0.0-SNAPSHOT"
    repository_url: 'http://54.161.129.104:8081/repository/master/'
    username: admin
    password: admin
    state: present
    dest: /opt/demo/
    mode: 0755
    force: yes  
    backup: "true"

- name: Ensure app is configured
  become: yes
  template:
    src: application.properties.j2
    dest: /opt/demo/application.properties

- name: Ensure logging is configured
  become: yes
  template:
    src: logback-spring.xml.j2
    dest: /opt/demo/logback-spring.xml

- name: Install demo systemd unit file
  become: yes
  template: src=demo.service.j2 dest=/etc/systemd/system/demo.service

- name: Start demo
  become: yes
  systemd: state=restarted name=demo daemon_reload=yes